AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31'
Description: AWS SAM Template for NWS Parser

Resources:
  SnowDepthFunction:
    Type: 'AWS::Serverless::Function'
    Properties:
      Handler: nws_parser.snow_depth
      Runtime: python3.12
      Events:
        ScheduledEvent:
          Type: Schedule
          Properties:
            Schedule: rate(1 hour)
      Environment:
        Variables:
          SNS_TOPIC_ARN: !Ref SNSTopic
      Policies:
        - SNSPublishMessagePolicy:
            TopicName: !GetAtt SNSTopic.TopicName
        - S3WritePolicy:
            BucketName: matthewparrilla.com
  SNSTopic:
    Type: 'AWS::SNS::Topic'
    Properties:
      Subscription:
        - Endpoint: "matthew.parrilla@gmail.com"
          Protocol: "email"

Outputs:
  SnowDepthFunction:
    Description: "Snow Depth Lambda Function ARN"
    Value: !GetAtt SnowDepthFunction.Arn

  SNSTopic:
    Description: "SNS Topic ARN for error notifications"
    Value: !Ref SNSTopic